### ISSUE TITLE
Holo-envoy can't update / rebuild due to lair-shim socket already in use

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-envoy#59]
Holo-envoy cannot rebuild / update due to the issue below. Manually fixed by deleting `/var/lib/holochain-rsm/` folder. Blocks upgrades

```
Feb 13 09:50:22 hpos holo-envoy[1954]: Starting Envoy server...
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.022Z [ index.js   ] SILLY: Initializing Envoy with input: {"NS":"/hosting/"}
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.024Z [ index.js   ] NORMA: Initializing with port (4656) and namespace (/hosting/)
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.029Z [ wss.js     ]  INFO: RPC WebSocket server 0.0.0.0:4656 >> Starting RPC WebSocket server on port 4656
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.030Z [ wss.js     ] DEBUG: RPC WebSocket server 0.0.0.0:4656 >> Registering method 'holo/wormhole/event' in namespace: /hosting/
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.030Z [ wss.js     ] DEBUG: RPC WebSocket server 0.0.0.0:4656 >> Registering method 'holo/wormhole/response' in namespace: /hosting/
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.030Z [ wss.js     ] DEBUG: RPC WebSocket server 0.0.0.0:4656 >> Registering method 'holo/agent/signup' in namespace: /hosting/
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.030Z [ wss.js     ] DEBUG: RPC WebSocket server 0.0.0.0:4656 >> Registering method 'holo/app_info' in namespace: /hosting/
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.030Z [ wss.js     ] DEBUG: RPC WebSocket server 0.0.0.0:4656 >> Registering method 'holo/call' in namespace: /hosting/
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.030Z [ wss.js     ] DEBUG: RPC WebSocket server 0.0.0.0:4656 >> Registering method 'holo/service/confirm' in namespace: /hosting/
Feb 13 09:50:22 hpos holo-envoy[1954]: 2021-02-13T09:50:22.030Z [ wormhole.j ] NORMA: init wormhole
Feb 13 09:50:22 hpos holo-envoy[1954]: Server has started on port: 4656
Feb 13 09:50:22 hpos holo-envoy[1954]: events.js:292
Feb 13 09:50:22 hpos holo-envoy[1954]:       throw er; // Unhandled 'error' event
Feb 13 09:50:22 hpos holo-envoy[1954]:       ^
Feb 13 09:50:22 hpos holo-envoy[1954]: Error: listen EADDRINUSE: address already in use /var/lib/holochain-rsm/lair-shim/socket
Feb 13 09:50:22 hpos holo-envoy[1954]:     at Server.setupListenHandle [as _listen2] (net.js:1296:21)
Feb 13 09:50:22 hpos holo-envoy[1954]:     at listenInCluster (net.js:1361:12)
Feb 13 09:50:22 hpos holo-envoy[1954]:     at Server.listen (net.js:1458:5)
Feb 13 09:50:22 hpos holo-envoy[1954]:     at Object.init (/nix/store/zw1fggksqxq03k1mnl5pd5sdxbfyrngb-holo-envoy/build/wormhole.js:57:8)
Feb 13 09:50:22 hpos holo-envoy[1954]:     at Envoy.<anonymous> (/nix/store/zw1fggksqxq03k1mnl5pd5sdxbfyrngb-holo-envoy/build/index.js:158:60)
Feb 13 09:50:22 hpos holo-envoy[1954]:     at step (/nix/store/zw1fggksqxq03k1mnl5pd5sdxbfyrngb-holo-envoy/build/index.js:46:23)
Feb 13 09:50:22 hpos holo-envoy[1954]:     at Object.next (/nix/store/zw1fggksqxq03k1mnl5pd5sdxbfyrngb-holo-envoy/build/index.js:27:53)
Feb 13 09:50:22 hpos holo-envoy[1954]:     at /nix/store/zw1fggksqxq03k1mnl5pd5sdxbfyrngb-holo-envoy/build/index.js:21:71
Feb 13 09:50:22 hpos holo-envoy[1954]:     at new Promise (<anonymous>)
Feb 13 09:50:22 hpos holo-envoy[1954]:     at __awaiter (/nix/store/zw1fggksqxq03k1mnl5pd5sdxbfyrngb-holo-envoy/build/index.js:17:12)
Feb 13 09:50:22 hpos holo-envoy[1954]: Emitted 'error' event on Server instance at:
Feb 13 09:50:22 hpos holo-envoy[1954]:     at emitErrorNT (net.js:1340:8)
Feb 13 09:50:22 hpos holo-envoy[1954]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Feb 13 09:50:22 hpos holo-envoy[1954]:   code: 'EADDRINUSE',
Feb 13 09:50:22 hpos holo-envoy[1954]:   errno: 'EADDRINUSE',
Feb 13 09:50:22 hpos holo-envoy[1954]:   syscall: 'listen',
Feb 13 09:50:22 hpos holo-envoy[1954]:   address: '/var/lib/holochain-rsm/lair-shim/socket',
Feb 13 09:50:22 hpos holo-envoy[1954]:   port: -1
Feb 13 09:50:22 hpos holo-envoy[1954]: }
```

**Comment by zo-el** [comment]
An easy solution for this will be in the holo-envoy service module we just update it to `rm -rf /var/lib/holochain-rsm/lair-shim/socket`

**Comment by alastairong** [comment]
Ok. If you get to it before me please update this issue.

**Comment by alastairong** [comment]
Probably fixed with https://github.com/Holo-Host/holo-nixpkgs/pull/694/commits/e7ae9b5ef47b3833ced887216fe121c5dae78d42

Will reopen if necessary

**Comment by zo-el** [comment]
I had already done this with [this commit](https://github.com/Holo-Host/holo-nixpkgs/pull/694/commits/deed7931844813599530b7946d2b5ce4615dfed9) .

**Comment by alastairong** [comment]
Fuck. I'm going to have to rebase this branch now.
