### ISSUE TITLE
Some buffer issue that borks the hosted happ

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-envoy#82]
```
Feb 25 17:49:18 hpos holo-envoy[779]: 2021-02-25T17:49:18.857Z [ index.js   ] SILLY: Set service request from Agent (uhCAkcN1hfGir0VYJ8--tiozpPq0J_qcxE0p2xwxar_jeXlz5MwUE) with signature (1p3qAxZskqamUd/I85iTibmsWB4ECUEsBgnizXiasrfAjQO1d5FaFOKRwTyZhMREpMfjOeIqauoKrQDyeSg/DA==)
Feb 25 17:49:18 hpos holo-envoy[779]: {
Feb 25 17:49:18 hpos holo-envoy[779]:     "agent_id": "uhCAkcN1hfGir0VYJ8--tiozpPq0J_qcxE0p2xwxar_jeXlz5MwUE",
Feb 25 17:49:18 hpos holo-envoy[779]:     "request": {
Feb 25 17:49:18 hpos holo-envoy[779]:         "timestamp": [
Feb 25 17:49:18 hpos holo-envoy[779]:             1614275359,
Feb 25 17:49:18 hpos holo-envoy[779]:             0
Feb 25 17:49:18 hpos holo-envoy[779]:         ],
Feb 25 17:49:18 hpos holo-envoy[779]:         "host_id": "uhCAkXxc0B3nyfctiKW1jpzUULGyBlPzZV1IZBLe1-13HRUslUv_K",
Feb 25 17:49:18 hpos holo-envoy[779]:         "call_spec": {
Feb 25 17:49:18 hpos holo-envoy[779]:             "hha_hash": "uhCkkDP7aytnEKH7BqkPXc9FnkHx3xm_cU0pUGWlsHNht4d4TG5mU",
Feb 25 17:49:18 hpos holo-envoy[779]:             "dna_alias": "elemental-chat",
Feb 25 17:49:18 hpos holo-envoy[779]:             "zome": "chat",
Feb 25 17:49:18 hpos holo-envoy[779]:             "function": "list_messages",
Feb 25 17:49:18 hpos holo-envoy[779]:             "args_hash": "EoIBeyJhY3RpdmVfY2hhdHRlciI6dHJ1ZSwiY2hhbm5lbCI6eyJjYXRlZ29yeSI6IkdlbmVyYWwiLCJ1dWlkIjoiZDg0MGE2MjktNTk4Ny00ZTA1LTg3ZjAtMGI1YjQ4MzA1YWRjIn0sImNodW5rIjp7ImVuZCI6MCwic3RhcnQiOjB9fQ=="
Feb 25 17:49:18 hpos holo-envoy[779]:         }
Feb 25 17:49:18 hpos holo-envoy[779]:     },
Feb 25 17:49:18 hpos holo-envoy[779]:     "request_signature": "1p3qAxZskqamUd/I85iTibmsWB4ECUEsBgnizXiasrfAjQO1d5FaFOKRwTyZhMREpMfjOeIqauoKrQDyeSg/DA=="
Feb 25 17:49:18 hpos holo-envoy[779]: }
Feb 25 17:49:18 hpos holo-envoy[779]: 2021-02-25T17:49:18.857Z [ index.js   ] DEBUG: Calling zome function chat->list_messages( channel : object, chunk : object, active_chatter : boolean ) on cell_id ([{"type":"Buffer","data":[132,45,36,189,224,81,149,254,17,189,207,158,51,133,18,85,64,4,97,45,164,158,7,37,171,8,150,14,11,18,105,68,220,181,134,180,220,173,84]},{"type":"Buffer","data":[132,32,36,112,221,97,124,104,171,209,86,9,243,239,173,138,140,233,62,173,9,254,167,49,19,74,118,199,12,90,175,248,222,94,92,249,51,5,4]}]), cap token (null), and provenance (uhCAkcN1hfGir0VYJ8--tiozpPq0J_qcxE0p2xwxar_jeXlz5MwUE):
Feb 25 17:49:18 hpos holo-envoy[779]: 2021-02-25T17:49:18.858Z [ index.js   ] ERROR: Failed during Conductor call: RangeError: Extra 2 of 3 byte(s) found at buffer[1]
Feb 25 17:49:18 hpos holo-envoy[779]: 2021-02-25T17:49:18.858Z [ index.js   ] FATAL: Conductor call threw unknown error: RangeError: Extra 2 of 3 byte(s) found at buffer[1]
Feb 25 17:49:18 hpos holo-envoy[779]: RangeError: Extra 2 of 3 byte(s) found at buffer[1]
Feb 25 17:49:18 hpos holo-envoy[779]:     at Decoder.createExtraByteError (/nix/store/74vpkcbqv97hz1j66sih9xdkixkf2gvz-holo-envoy/node_modules/@msgpack/msgpack/dist/Decoder.js:78:16)
Feb 25 17:49:18 hpos holo-envoy[779]:     at Decoder.decode (/nix/store/74vpkcbqv97hz1j66sih9xdkixkf2gvz-holo-envoy/node_modules/@msgpack/msgpack/dist/Decoder.js:85:24)
Feb 25 17:49:18 hpos holo-envoy[779]:     at Object.decode (/nix/store/74vpkcbqv97hz1j66sih9xdkixkf2gvz-holo-envoy/node_modules/@msgpack/msgpack/dist/decode.js:14:20)
Feb 25 17:49:18 hpos holo-envoy[779]:     at Envoy.<anonymous> (/nix/store/74vpkcbqv97hz1j66sih9xdkixkf2gvz-holo-envoy/build/index.js:569:72)
Feb 25 17:49:18 hpos holo-envoy[779]:     at step (/nix/store/74vpkcbqv97hz1j66sih9xdkixkf2gvz-holo-envoy/build/index.js:57:23)
Feb 25 17:49:18 hpos holo-envoy[779]:     at Object.next (/nix/store/74vpkcbqv97hz1j66sih9xdkixkf2gvz-holo-envoy/build/index.js:38:53)
Feb 25 17:49:18 hpos holo-envoy[779]:     at fulfilled (/nix/store/74vpkcbqv97hz1j66sih9xdkixkf2gvz-holo-envoy/build/index.js:29:58)
Feb 25 17:49:18 hpos holo-envoy[779]:     at runMicrotasks (<anonymous>)
Feb 25 17:49:18 hpos holo-envoy[779]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Feb 25 17:49:18 hpos holo-envoy[779]: 2021-02-25T17:49:18.860Z [ wss.js     ] ERROR: Handler 'holo/call' threw an error: TypeError: Value is required
Feb 25 17:49:34 hpos holo-envoy[779]: 2021-02-25T17:49:34.630Z [ index.js   ] ERROR: Failed during signing request #78 with timeout (20000ms)
```

Seen in browser logs as:
```
Attached payload signature (yq2WS+oNx80k44yq7p3+mYw2XVUV4om7wrs6dgd+pxaPH0M/6f8HiwaQhc2D+aeE6wWTlUPBMSZd7NDESapoAg==) from Agent (uhCAkCX6GUmgSDXHqnQR1Mnj8S4tzWWisdKQGTJge20nTJHiyQvYv)
2.holo_hosting_chaperone.js:1 Sending request signature yq2WS+oNx80k44yq7p3+mYw2XVUV4om7wrs6dgd+pxaPH0M/6f8HiwaQhc2D+aeE6wWTlUPBMSZd7NDESapoAg== to Envoy
2.holo_hosting_chaperone.js:1 {code: -32000, message: "TypeError", data: "Value is required"}
elementalChat.js:13 1614276848204 "signalMessageSent zome done"
```

**Comment by alastairong** [comment]
At some point during testing sign ups and zome calls I got this issue. Not sure what it is but:
1) I can't make any zome calls anymore
2) It is not specific to an individual hosted instance. This issue persists with newly signed up agents

My  guess is that it's service-logger related since there's only 1 service log?

**Comment by zo-el** [comment]
@alastairong can you try hard reloading the browser or use incognito mode?

**Comment by alastairong** [comment]
I didn't try that. I can do. But I did clear the indexDB and this was still an issue

**Comment by timotree3** [comment]
This is a message pack error. So it seems like the UI may not be up to date with the latest messagepack changes to envoy. That's why joel said to reload because even if you've deployed the updated UI it may not have loaded in the browser

**Comment by alastairong** [comment]
Going to assume resolved for now and re-open if needed
