### ISSUE TITLE
Envoy Timeout Issues

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-envoy#96]
Envoy works fine until it suddenly starts encountering lots of timeout issues. It may even freeze up (logs frozen). Once Envoy is in this state it requires restart / reboot. This seems to occur at any point - sign in, creating channels, posting messages, calling listChannel or listMessage, or logging out.

```
Mar 05 11:16:54 hpos holo-envoy[778]: CONDUCTOR CALL ERROR:
Mar 05 11:16:54 hpos holo-envoy[778]: Error: Timed out in 30000ms: zome_call_invocation
Mar 05 11:16:54 hpos holo-envoy[778]:     at Timeout.<anonymous> (/nix/store/zyfrzxgpr7xc1n9hbgfx1yp9m5adjxwq-holo-envoy/node_modules/@holochain/conductor-api/lib/websocket/common.js:16:20)
Mar 05 11:16:54 hpos holo-envoy[778]:     at listOnTimeout (internal/timers.js:549:17)
Mar 05 11:16:54 hpos holo-envoy[778]:     at processTimers (internal/timers.js:492:7)
Mar 05 11:16:54 hpos holo-envoy[778]: 2021-03-05T11:16:54.172Z [ index.js   ] ERROR: Failed during Conductor call with error: Error: CONDUCTOR CALL ERROR: {}
Mar 05 11:16:54 hpos holo-envoy[778]: 2021-03-05T11:16:54.172Z [ index.js   ] ERROR: Failed during Conductor call: HoloError: Error: CONDUCTOR CALL ERROR: {}
Mar 05 11:16:54 hpos holo-envoy[778]: 2021-03-05T11:16:54.173Z [ index.js   ]  WARN: Setting error response to raised HoloError: HoloError: Error: CONDUCTOR CALL ERROR: {}
Mar 05 11:16:54 hpos holo-envoy[778]: 2021-03-05T11:16:54.173Z [ index.js   ] NORMA: Returning error: 
Mar 05 11:16:55 hpos holo-envoy[778]: CONDUCTOR CALL ERROR:
Mar 05 11:16:55 hpos holo-envoy[778]: Error: Timed out in 30000ms: zome_call_invocation
Mar 05 11:16:55 hpos holo-envoy[778]:     at Timeout.<anonymous> (/nix/store/zyfrzxgpr7xc1n9hbgfx1yp9m5adjxwq-holo-envoy/node_modules/@holochain/conductor-api/lib/websocket/common.js:16:20)
Mar 05 11:16:55 hpos holo-envoy[778]:     at listOnTimeout (internal/timers.js:549:17)
Mar 05 11:16:55 hpos holo-envoy[778]:     at processTimers (internal/timers.js:492:7)
Mar 05 11:16:55 hpos holo-envoy[778]: 2021-03-05T11:16:55.291Z [ index.js   ] ERROR: Failed during Conductor call with error: Error: CONDUCTOR CALL ERROR: {}
Mar 05 11:16:55 hpos holo-envoy[778]: 2021-03-05T11:16:55.292Z [ index.js   ] ERROR: Failed during Conductor call: HoloError: Error: CONDUCTOR CALL ERROR: {}
Mar 05 11:16:55 hpos holo-envoy[778]: 2021-03-05T11:16:55.292Z [ index.js   ]  WARN: Setting error response to raised HoloError: HoloError: Error: CONDUCTOR CALL ERROR: {}
Mar 05 11:16:55 hpos holo-envoy[778]: 2021-03-05T11:16:55.292Z [ index.js   ] NORMA: Returning error: 
Mar 05 11:16:55 hpos holo-envoy[778]: 2021-03-05T11:16:55.427Z [ index.js   ] SILLY: Incoming websocket message: {"jsonrpc":"2.0","method":"holo/call","params":{"anonymous":false,"agent_id":"uhCAkgXB14NzDbxZ-z8F0gfHmOJQrdhusPtsC0j7KlRk3bLpVOveU","payload":{"timestamp":[1614943015,0],"host_id":"uhCAkXxc0B3nyfctiKW1jpzUULGyBlPzZV1IZBLe1-13HRUslUv_K","call_spec":{"cell_id":[{"type":"Buffer","data":[132,45,36,10,149,226,187,233,242,168,78,37,152,67,31,92,91,23,176,197,130,14,114,252,7,217,186,242,46,62,179,32,31,241,113,75,34,87,170]},{"type":"Buffer",
```

**Comment by alastairong** [comment]
Closed by #98
